### PR TITLE
Update Infector runtime to 46

### PR DESCRIPTION
**Pull request by yakushabb**
- Update Infector runtime to 46 since runtime version 44 has reached end-of-life.
- Update appdata information to Appstream 1.0 specs.

More information: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/

### CODE REVIEW

**Comment by ghost** [comment]
Hi @mangobrain,

I've updated the Infector runtime to version 46 as runtime version 44 has reached end-of-life. The x86_64 version was successful, but the aarch64 version failed. Could you review the changes? 

Thanks.

**Comment by ghost** [comment]
@barthalion I've updated the Infector runtime to version 46.

**Comment by yakushabb** [comment]
This pr was merged a few months ago. Flathub still contains a warning about EOL runtime 

https://flathub.org/apps/uk.co.mangobrain.Infector

> over 6 years ago (Built over 1 year ago)
> Infector is potentially unsafe
> Uses an end-of-life runtime

**Comment by ghost** [comment]
@bbhtt @barthalion 

This PR was merged a few months ago, but Flathub still shows a warning about the EOL runtime.

Source: https://flathub.org/apps/uk.co.mangobrain.Infector

```
    over 6 years ago (Built over 1 year ago)
    Infector is potentially unsafe
    Uses an end-of-life runtime
```

**Comment by bbhtt** [comment]
restarted build

**Pull request merged**
